# Generated by Django 5.0.1 on 2024-02-09 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(default=None, upload_to='media/thumbnails', verbose_name='Мініатюра')),
                ('name', models.CharField(max_length=50, verbose_name='Назва лоту')),
                ('description', models.TextField(blank=True, max_length=700, null=True, verbose_name='Короткий опис (до 700 символів)')),
                ('start_price', models.FloatField(verbose_name='Перша ставка в $')),
                ('expiration_date', models.DateTimeField(null=True, verbose_name='Час завершення аукціону')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lots.tag', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'лот',
                'verbose_name_plural': 'Лоти',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lots.lot')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(verbose_name='Ставка')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lots.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lots.lot')),
            ],
            options={
                'verbose_name': 'зображення лоту',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=700, verbose_name='Текст повідомлення')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
