# Generated by Django 5.0.1 on 2024-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='poster',
            field=models.ImageField(default='None', upload_to='tags/'),
        ),
    ]
